config/routes.rb
SimpleFixed::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :projects, :only => [:create, :destroy, :show]
  resources :groups
  resources :basecases, :only => [:create, :destroy, :show]
  resources :annuals
  resources :borrowings
  resources :scenarios, :only => [:create, :destroy, :show]
  resources :actannuals
  resources :actborrowings
  resources :swapcurves
  resources :forwardcurves
  resources :fxrates
  resources :riskpremia
  resources :choleskies
  resources :choleskyirs

  match '/signup',      :to => 'users#new'
  match '/demo',        :to => 'pages#demo'
  match '/about',       :to => 'pages#about'
  match '/pricing',     :to => 'pages#pricing'
  match '/environment', :to => 'pages#environment'  

  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => 'pages#home'

 end

app/models/group.rb
class Group < ActiveRecord::Base

    attr_accessible :group_name

    has_many :users,    :dependent => :destroy
    has_many :basecases, :dependent => :destroy

    has_many :projects, :through => :users

    validates :group_name, :presence => true,
                           :uniqueness => { :case_sensitive => false } 

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_filter :authorized_superadmin, :only => [:index] 
  before_filter :authorized_admin, :only => [:show] 
  before_filter :authorized_group_member, :only => [:show]

  def new
      @group = Group.new
      @title = "New group"
  end

  def show
      @group = Group.find(params[:id])
      @users = @group.users
      @basecases = @group.basecases
      @title = @group.group_name
      @user = User.new if signed_in?
      @basecase = Basecase.new if signed_in? 
  end

  def create
    @group = Group.new(params[:group])
    if @group.save 
      flash[:success] = "You have created a new group"
      redirect_to @group
    else
      @title = "New group"
      render 'new'
    end
  end

  def edit
      @group = Group.find(params[:id])  
      @title = "Edit group" 
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      flash[:success] = "Group updated"
      redirect_to @group
    else
      @title = "Edit group"
      render 'edit'
    end
  end
 
  def index
    @title = "All groups"
    @groups = Group.all
  end

  def destroy
    Group.find(params[:id]).destroy
    flash[:success] = "Group deleted"
    redirect_to groups_path
  end

  private

      def authorized_superadmin
          redirect_to root_path unless current_user_superadmin(current_user)
      end

      def authorized_admin
          @group = Group.find(params[:id])
          redirect_to root_path unless current_user_admin(current_user, @group)
      end

      def authorized_group_member
          @group = Group.find(params[:id]) 
          redirect_to root_path unless (@group.id == current_user.group_id  || current_user.name == 'mandeep3')
      end
  
end

app/views/groups/_group.html.erb
<li>
  <%=link_to group.group_name, group %>
</li>

app/views/groups/edit.html.erb
<h1>Edit group</h1>

<%= form_for(@group) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :group_name %><br />
    <%= f.text_field :group_name %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/groups/index.html.erb
<p><%= link_to "Add new group", new_group_path %></p>


<h1>All groups</h1>

<ul class="groups">
  <%= render @groups %>
</ul>

app/views/groups/new.html.erb
<h1>Create group</h1>

<%= form_for(@group) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :group_name %><br />
    <%= f.text_field :group_name %>
  </div>
  <div class="actions">
    <%= f.submit "Create group" %>
  </div>
<% end %>

app/views/groups/show.html.erb
<h1>
  <%= @group.group_name %> 
</h1>


<h3>
   Financial data
</h3>  

  <% @basecases.each do |basecase| %>
     <li>
       <%= link_to 'Update your business financials', basecase %>
       <%if current_user.name == 'mandeep3' %>

              <%= link_to "delete", basecase,   :method => :delete,
                                                :confirm => "You sure?" %>
      <% end%>
     </li>
  <% end %>

<br/><br/>
<hr>

<table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <%= render 'shared/user_form' %>
      </td>
    </tr>
</table>

<hr>

<h3>Current group members</h3>
<% @users.each do |user| %>
   <li>
     <%= link_to user.name, user %>
     <%if user.admin? %>
            <%= link_to "delete", user,   :method => :delete,
                                          :confirm => "You sure?",
                                          :title => user.name %>
     <% end%>
   </li>
<% end %>

<% if @group.basecases.count < 1 %>
  <% if current_user.name == 'mandeep3' %>
    <table class="front" summary="For signed-in users">
        <tr>
          <td class="main">
            <%= render 'shared/basecase_form' %>
          </td>
        </tr>
    </table>
  <% end %>
<% end %>